language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.2

before_script:
  # Setup test Postgres database.
  - psql -c 'create database app_config_test;' -U postgres
  - psql -d app_config_test -U postgres -c 'CREATE TABLE app_config (id bigserial primary key, admin_email character varying(255), api_name character varying(255), api_key character varying(255), true_option boolean, false_option boolean);'
  - psql -d app_config_test -U postgres -c "INSERT INTO app_config (admin_email, api_name, api_key, true_option, false_option) VALUES ('admin@example.com', 'Supr Webz 2.0', 'SUPERAWESOMESERVICE', true, false);"
  # Setup test MySQL database.
  - mysql -u root -e 'create database app_config_test;'
  - mysql -u root -D app_config_test -e 'CREATE TABLE app_config (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, admin_email VARCHAR(255), api_name VARCHAR(255), api_key VARCHAR(255), true_option BOOLEAN, false_option BOOLEAN);'
  - mysql -u root -D app_config_test -e "INSERT INTO app_config (admin_email, api_key, true_option, false_option) VALUES ('admin@example.com', 'Supr Webz 2.0', 'SUPERAWESOMESERVICE', true, false);"

env:
  # Ignore warnings when running specs.
  - RUBYOPT="-W0"

branches:
  only:
    - master

services:
  - mongodb
  - postgres
