language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0

env:
  # Ignore warnings when running specs.
  - RUBYOPT="-W0"

branches:
  only:
    - master

before_install:
  # Install and start MongoDB so we can test that storage method.
  - sudo apt-get update -qq
  - sudo apt-get install -qq mongodb
  - sudo service mongodb start
