version: '2'
services:
  mongo_db:
    image: mongo

  mysql_db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: app_config_test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # Need to quote 'yes' since YAML interprets that as a boolean.

  postgres_db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: app_config_test

  app_config:
    build: .
    command: bundle exec rake spec
    volumes:
      - .:/app_config
    depends_on:
      - mongo_db
      - mysql_db
      - postgres_db
