name: Run Tests
on:
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        ruby: [2.6]

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: app_config_test

      mysql:
        image: mariadb:latest
        env:
          MYSQL_USER: runner
          MYSQL_DATABASE: app_config_test
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # Need to quote 'yes' since YAML interprets that as a boolean.

      mongo:
        image: mongo
        ports:
          - 27017:27017

    name: Test ${{ matrix.ruby }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Setup System Dependencies
      run: |
        sudo apt-get update && \
        sudo apt-get install libmysqlclient-dev libpq-dev libsqlite3-dev

    - name: Setup App Dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run Tests
      run: POSTGRES_HOST=localhost MYSQL_HOST=localhost MONGO_HOST=localhost bundle exec rake spec
